/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadprojectcrickzie;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CreateTournament extends javax.swing.JFrame {

    /**
     * Creates new form CreateTournament
     */
    public CreateTournament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@DESKTOP-1HKAK02:1521:XEPU").createEntityManager();
        playerQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Player p");
        playerList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : playerQuery.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TournamentName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TournamentYear = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TeamNumber = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Knockout = new javax.swing.JRadioButton();
        LeagueAndKnockout = new javax.swing.JRadioButton();
        League = new javax.swing.JRadioButton();
        KnockoutAndLeague = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();

        setTitle("Tournament");

        jLabel1.setText("Tournament Name:");

        TournamentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TournamentNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Tournament Year:");

        TournamentYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", " " }));
        TournamentYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TournamentYearActionPerformed(evt);
            }
        });

        jLabel3.setText("Number of Teams:");

        TeamNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6" }));
        TeamNumber.setEnabled(false);
        TeamNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamNumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Format:");

        buttonGroup1.add(Knockout);
        Knockout.setText("Knockout");
        Knockout.setEnabled(false);
        Knockout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnockoutActionPerformed(evt);
            }
        });

        buttonGroup1.add(LeagueAndKnockout);
        LeagueAndKnockout.setSelected(true);
        LeagueAndKnockout.setText("League + Knockout");

        buttonGroup1.add(League);
        League.setText("League");
        League.setEnabled(false);

        buttonGroup1.add(KnockoutAndLeague);
        KnockoutAndLeague.setText("Knockout + League");
        KnockoutAndLeague.setEnabled(false);
        KnockoutAndLeague.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnockoutAndLeagueActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel5.setText("Crickzie");
        jLabel5.setToolTipText("");

        Logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icon.png")); // NOI18N

        Submit.setText("Create Tournament");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(League)
                            .addComponent(LeagueAndKnockout)
                            .addComponent(Knockout)
                            .addComponent(KnockoutAndLeague)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Submit)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TournamentName)
                                    .addComponent(TournamentYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TeamNumber, 0, 185, Short.MAX_VALUE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(Logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TournamentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TournamentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Knockout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeagueAndKnockout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KnockoutAndLeague)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(League)
                .addGap(18, 18, 18)
                .addComponent(Submit)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TournamentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TournamentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TournamentNameActionPerformed

    private void TournamentYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TournamentYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TournamentYearActionPerformed

    private void TeamNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamNumberActionPerformed

    private void KnockoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnockoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnockoutActionPerformed

    private void KnockoutAndLeagueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnockoutAndLeagueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KnockoutAndLeagueActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String Name = TournamentName.getText();
        int TeamCount = Integer.parseInt(TeamNumber.getItemAt(TeamNumber.getSelectedIndex()));
        int Year = Integer.parseInt(TournamentYear.getItemAt(TournamentYear.getSelectedIndex()));
        int val=JDBConnection.JDBCCreateTournament(Name, Year, TeamCount, 1);
        if(val>0){
            JOptionPane.showMessageDialog(rootPane, "Tournament", "Tournament Created", 1);
            SelectTeams st = new SelectTeams(val);
            st.setVisible(true);
            this.setVisible(false);
            
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Tournament", "Tournament Creation Failed", 1);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTournament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Knockout;
    private javax.swing.JRadioButton KnockoutAndLeague;
    private javax.swing.JRadioButton League;
    private javax.swing.JRadioButton LeagueAndKnockout;
    private javax.swing.JLabel Logo1;
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> TeamNumber;
    private javax.swing.JTextField TournamentName;
    private javax.swing.JComboBox<String> TournamentYear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.util.List<sadprojectcrickzie.Player> playerList;
    private javax.persistence.Query playerQuery;
    // End of variables declaration//GEN-END:variables
}
