/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadprojectcrickzie;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {
    LoginWindow loginWindow = new LoginWindow();
    CreateMatch createMatch = new CreateMatch();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewMatch = new javax.swing.JButton();
        PlayerCreate = new javax.swing.JButton();
        TeamCreate = new javax.swing.JButton();
        MatchCreate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Welcome = new javax.swing.JLabel();
        CreationText = new javax.swing.JLabel();
        TournamentCreate = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logo1 = new javax.swing.JLabel();
        ViewTournament = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crickzie Main Menu");

        ViewMatch.setText("View Match");
        ViewMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMatchActionPerformed(evt);
            }
        });

        PlayerCreate.setText("Player");
        PlayerCreate.setEnabled(false);
        PlayerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerCreateActionPerformed(evt);
            }
        });

        TeamCreate.setText("Team");
        TeamCreate.setEnabled(false);
        TeamCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamCreateActionPerformed(evt);
            }
        });

        MatchCreate.setText("Match");
        MatchCreate.setEnabled(false);
        MatchCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchCreateActionPerformed(evt);
            }
        });

        CreationText.setText("Creation Panel");

        TournamentCreate.setText("Tournament");
        TournamentCreate.setEnabled(false);
        TournamentCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TournamentCreateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel2.setLabelFor(Logo);
        jLabel2.setText("Crickzie");
        jLabel2.setToolTipText("");

        Logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\icon.png")); // NOI18N

        ViewTournament.setText("View Tournament");
        ViewTournament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTournamentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TournamentCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ViewMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewTournament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TeamCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatchCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreationText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(ViewMatch)
                .addGap(18, 18, 18)
                .addComponent(ViewTournament)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreationText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(31, 31, 31)
                .addComponent(PlayerCreate)
                .addGap(18, 18, 18)
                .addComponent(TeamCreate)
                .addGap(18, 18, 18)
                .addComponent(MatchCreate)
                .addGap(18, 18, 18)
                .addComponent(TournamentCreate)
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMatchActionPerformed
        // TODO add your handling code here:
        FindMatch fm = new FindMatch();
        fm.setVisible(true);
    }//GEN-LAST:event_ViewMatchActionPerformed

    private void PlayerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerCreateActionPerformed
        // TODO add your handling code here:
        CreatePlayer cp = new CreatePlayer();
        cp.setVisible(true);
    }//GEN-LAST:event_PlayerCreateActionPerformed

    private void TeamCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamCreateActionPerformed
        // TODO add your handling code here:
        CreateTeam ct = new CreateTeam();
        ct.setVisible(true);
    }//GEN-LAST:event_TeamCreateActionPerformed

    private void MatchCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchCreateActionPerformed
        // TODO add your handling code here:
        CreateMatch cm = new CreateMatch();
        cm.setVisible(true);
    }//GEN-LAST:event_MatchCreateActionPerformed

    private void TournamentCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TournamentCreateActionPerformed
        // TODO add your handling code here:
        CreateTournament ct = new CreateTournament();
        ct.setVisible(true);
    }//GEN-LAST:event_TournamentCreateActionPerformed

    private void ViewTournamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTournamentActionPerformed
        // TODO add your handling code here:
        Standings st = new Standings();
        st.setVisible(true);
    }//GEN-LAST:event_ViewTournamentActionPerformed
    public void update(){
        Welcome.setText(SADProjectCrickzie.CurrentName+", welcome to crickzie.");
        System.out.println(SADProjectCrickzie.CurrentType);
        if(SADProjectCrickzie.CurrentType==1){
            this.PlayerCreate.setEnabled(true);
            this.MatchCreate.setEnabled(true);
            this.TeamCreate.setEnabled(true);
            this.TournamentCreate.setEnabled(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreationText;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JButton MatchCreate;
    private javax.swing.JButton PlayerCreate;
    private javax.swing.JButton TeamCreate;
    private javax.swing.JButton TournamentCreate;
    private javax.swing.JButton ViewMatch;
    private javax.swing.JButton ViewTournament;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
