/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadprojectcrickzie;

/**
 *
 * @author User
 */
public class PlayerSelection extends javax.swing.JFrame {
    public int Toss;
    public int Team1ID;
    public int Team2ID;
    public int Overs;
    /**
     * Creates new form PlayerSelection
     * @param T1
     * @param T2
     * @param _Toss
     */
    public PlayerSelection(int T1, int T2, int _Toss, int _overs) {
        Team1ID = T1;
        Team2ID = T2;
        Toss = _Toss;
        Overs=_overs;
        initComponents();
        
    }
    
    public void putTeams(String TeamName1, String TeamName2){
        this.Team1.setText(TeamName1);
        this.Team2.setText(TeamName2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerLabel1 = new javax.swing.JLabel();
        Player1 = new javax.swing.JTextField();
        PlayerLabel2 = new javax.swing.JLabel();
        Player2 = new javax.swing.JTextField();
        PlayerLabel3 = new javax.swing.JLabel();
        Player3 = new javax.swing.JTextField();
        PlayerLabel4 = new javax.swing.JLabel();
        Player4 = new javax.swing.JTextField();
        PlayerLabel5 = new javax.swing.JLabel();
        Player5 = new javax.swing.JTextField();
        Player6 = new javax.swing.JTextField();
        PlayerLabel6 = new javax.swing.JLabel();
        Player7 = new javax.swing.JTextField();
        PlayerLabel7 = new javax.swing.JLabel();
        PlayerLabel8 = new javax.swing.JLabel();
        Player8 = new javax.swing.JTextField();
        Player9 = new javax.swing.JTextField();
        PlayerLabel9 = new javax.swing.JLabel();
        PlayerLabel10 = new javax.swing.JLabel();
        Player10 = new javax.swing.JTextField();
        PlayerLabel11 = new javax.swing.JLabel();
        Player11 = new javax.swing.JTextField();
        Player12 = new javax.swing.JTextField();
        Player2Label5 = new javax.swing.JLabel();
        Player13 = new javax.swing.JTextField();
        Player14 = new javax.swing.JTextField();
        Player2Label6 = new javax.swing.JLabel();
        Player15 = new javax.swing.JTextField();
        Player2Label7 = new javax.swing.JLabel();
        Player2Label8 = new javax.swing.JLabel();
        Player16 = new javax.swing.JTextField();
        Player17 = new javax.swing.JTextField();
        Player2Label9 = new javax.swing.JLabel();
        Player2Label10 = new javax.swing.JLabel();
        Player18 = new javax.swing.JTextField();
        Player2Label1 = new javax.swing.JLabel();
        Player2Label11 = new javax.swing.JLabel();
        Player19 = new javax.swing.JTextField();
        Player20 = new javax.swing.JTextField();
        Player2Label2 = new javax.swing.JLabel();
        Player21 = new javax.swing.JTextField();
        Player2Label3 = new javax.swing.JLabel();
        Player22 = new javax.swing.JTextField();
        Player2Label4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Team1 = new javax.swing.JLabel();
        Team2 = new javax.swing.JLabel();
        Create = new javax.swing.JButton();
        AutoGen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();

        setTitle("Player Selection");

        PlayerLabel1.setText("Player1");
        PlayerLabel1.setPreferredSize(new java.awt.Dimension(100, 14));

        Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1ActionPerformed(evt);
            }
        });
        Player1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player1KeyReleased(evt);
            }
        });

        PlayerLabel2.setText("Player2");
        PlayerLabel2.setPreferredSize(new java.awt.Dimension(100, 14));

        Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player2ActionPerformed(evt);
            }
        });
        Player2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player2KeyReleased(evt);
            }
        });

        PlayerLabel3.setText("Player3");
        PlayerLabel3.setPreferredSize(new java.awt.Dimension(100, 14));

        Player3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player3ActionPerformed(evt);
            }
        });
        Player3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player3KeyReleased(evt);
            }
        });

        PlayerLabel4.setText("Player4");
        PlayerLabel4.setPreferredSize(new java.awt.Dimension(100, 14));

        Player4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player4ActionPerformed(evt);
            }
        });
        Player4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player4KeyReleased(evt);
            }
        });

        PlayerLabel5.setText("Player5");
        PlayerLabel5.setPreferredSize(new java.awt.Dimension(100, 14));

        Player5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player5ActionPerformed(evt);
            }
        });
        Player5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player5KeyReleased(evt);
            }
        });

        Player6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player6ActionPerformed(evt);
            }
        });
        Player6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player6KeyReleased(evt);
            }
        });

        PlayerLabel6.setText("Player6");
        PlayerLabel6.setPreferredSize(new java.awt.Dimension(100, 14));

        Player7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player7ActionPerformed(evt);
            }
        });
        Player7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player7KeyReleased(evt);
            }
        });

        PlayerLabel7.setText("Player7");
        PlayerLabel7.setPreferredSize(new java.awt.Dimension(100, 14));

        PlayerLabel8.setText("Player8");
        PlayerLabel8.setPreferredSize(new java.awt.Dimension(100, 14));

        Player8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player8ActionPerformed(evt);
            }
        });
        Player8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player8KeyReleased(evt);
            }
        });

        Player9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player9ActionPerformed(evt);
            }
        });
        Player9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player9KeyReleased(evt);
            }
        });

        PlayerLabel9.setText("Player9");
        PlayerLabel9.setPreferredSize(new java.awt.Dimension(100, 14));

        PlayerLabel10.setText("Player10");
        PlayerLabel10.setPreferredSize(new java.awt.Dimension(100, 14));

        Player10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player10ActionPerformed(evt);
            }
        });
        Player10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player10KeyReleased(evt);
            }
        });

        PlayerLabel11.setText("Player11");
        PlayerLabel11.setPreferredSize(new java.awt.Dimension(100, 14));

        Player11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player11ActionPerformed(evt);
            }
        });
        Player11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player11KeyReleased(evt);
            }
        });

        Player12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player12ActionPerformed(evt);
            }
        });
        Player12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player12KeyReleased(evt);
            }
        });

        Player2Label5.setText("Player5");
        Player2Label5.setPreferredSize(new java.awt.Dimension(100, 14));

        Player13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player13ActionPerformed(evt);
            }
        });
        Player13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player13KeyReleased(evt);
            }
        });

        Player14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player14ActionPerformed(evt);
            }
        });
        Player14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player14KeyReleased(evt);
            }
        });

        Player2Label6.setText("Player6");
        Player2Label6.setPreferredSize(new java.awt.Dimension(100, 14));

        Player15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player15ActionPerformed(evt);
            }
        });
        Player15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player15KeyReleased(evt);
            }
        });

        Player2Label7.setText("Player7");
        Player2Label7.setPreferredSize(new java.awt.Dimension(100, 14));

        Player2Label8.setText("Player8");
        Player2Label8.setPreferredSize(new java.awt.Dimension(100, 14));

        Player16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player16ActionPerformed(evt);
            }
        });
        Player16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player16KeyReleased(evt);
            }
        });

        Player17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player17ActionPerformed(evt);
            }
        });
        Player17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player17KeyReleased(evt);
            }
        });

        Player2Label9.setText("Player9");
        Player2Label9.setPreferredSize(new java.awt.Dimension(100, 14));

        Player2Label10.setText("Player10");
        Player2Label10.setPreferredSize(new java.awt.Dimension(100, 14));

        Player18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player18ActionPerformed(evt);
            }
        });
        Player18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player18KeyReleased(evt);
            }
        });

        Player2Label1.setText("Player1");
        Player2Label1.setPreferredSize(new java.awt.Dimension(100, 14));

        Player2Label11.setText("Player11");
        Player2Label11.setPreferredSize(new java.awt.Dimension(100, 14));

        Player19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player19ActionPerformed(evt);
            }
        });
        Player19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player19KeyReleased(evt);
            }
        });

        Player20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player20ActionPerformed(evt);
            }
        });
        Player20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player20KeyReleased(evt);
            }
        });

        Player2Label2.setText("Player2");
        Player2Label2.setPreferredSize(new java.awt.Dimension(100, 14));

        Player21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player21ActionPerformed(evt);
            }
        });
        Player21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player21KeyReleased(evt);
            }
        });

        Player2Label3.setText("Player3");
        Player2Label3.setPreferredSize(new java.awt.Dimension(100, 14));

        Player22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player22ActionPerformed(evt);
            }
        });
        Player22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Player22KeyReleased(evt);
            }
        });

        Player2Label4.setText("Player4");
        Player2Label4.setPreferredSize(new java.awt.Dimension(100, 14));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Team1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team1.setText("Team1");

        Team2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Team2.setText("Team2");

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        AutoGen.setText("Auto");
        AutoGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoGenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel5.setText("Crickzie");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PlayerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PlayerLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Player11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Team1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 22, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Create)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Player2Label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Player2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Player22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Player12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Player21, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Team2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AutoGen)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Create)
                            .addComponent(AutoGen))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Team2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Player22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2Label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Team1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlayerLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Player11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player1ActionPerformed

    private void Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player2ActionPerformed

    private void Player3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player3ActionPerformed

    private void Player4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player4ActionPerformed

    private void Player5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player5ActionPerformed

    private void Player6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player6ActionPerformed

    private void Player7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player7ActionPerformed

    private void Player8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player8ActionPerformed

    private void Player9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player9ActionPerformed

    private void Player10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player10ActionPerformed

    private void Player11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player11ActionPerformed

    private void Player12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player12ActionPerformed

    private void Player13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player13ActionPerformed

    private void Player14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player14ActionPerformed

    private void Player15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player15ActionPerformed

    private void Player16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player16ActionPerformed

    private void Player17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player17ActionPerformed

    private void Player18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player18ActionPerformed

    private void Player19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player19ActionPerformed

    private void Player20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player20ActionPerformed

    private void Player21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player21ActionPerformed

    private void Player22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player22ActionPerformed

    private void Player1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player1KeyReleased
        // TODO add your handling code here:
        PlayerLabel1.setText(JDBConnection.JDBCGetPlayer(Player1.getText()));
    }//GEN-LAST:event_Player1KeyReleased

    private void Player2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player2KeyReleased
        // TODO add your handling code here:
        PlayerLabel2.setText(JDBConnection.JDBCGetPlayer(Player2.getText()));
    }//GEN-LAST:event_Player2KeyReleased

    private void Player3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player3KeyReleased
        // TODO add your handling code here:
        PlayerLabel3.setText(JDBConnection.JDBCGetPlayer(Player3.getText()));
    }//GEN-LAST:event_Player3KeyReleased

    private void Player4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player4KeyReleased
        // TODO add your handling code here:
        PlayerLabel4.setText(JDBConnection.JDBCGetPlayer(Player4.getText()));
    }//GEN-LAST:event_Player4KeyReleased

    private void Player5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player5KeyReleased
        // TODO add your handling code here:
        PlayerLabel5.setText(JDBConnection.JDBCGetPlayer(Player5.getText()));
    }//GEN-LAST:event_Player5KeyReleased

    private void Player6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player6KeyReleased
        // TODO add your handling code here:
        PlayerLabel6.setText(JDBConnection.JDBCGetPlayer(Player6.getText()));
    }//GEN-LAST:event_Player6KeyReleased

    private void Player7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player7KeyReleased
        // TODO add your handling code here:
        PlayerLabel7.setText(JDBConnection.JDBCGetPlayer(Player7.getText()));
    }//GEN-LAST:event_Player7KeyReleased

    private void Player8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player8KeyReleased
        // TODO add your handling code here:
        PlayerLabel8.setText(JDBConnection.JDBCGetPlayer(Player8.getText()));
    }//GEN-LAST:event_Player8KeyReleased

    private void Player9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player9KeyReleased
        // TODO add your handling code here:
        PlayerLabel9.setText(JDBConnection.JDBCGetPlayer(Player9.getText()));
    }//GEN-LAST:event_Player9KeyReleased

    private void Player10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player10KeyReleased
        // TODO add your handling code here:
        PlayerLabel10.setText(JDBConnection.JDBCGetPlayer(Player10.getText()));
    }//GEN-LAST:event_Player10KeyReleased

    private void Player11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player11KeyReleased
        // TODO add your handling code here:
        PlayerLabel11.setText(JDBConnection.JDBCGetPlayer(Player11.getText()));
    }//GEN-LAST:event_Player11KeyReleased

    private void Player12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player12KeyReleased
        // TODO add your handling code here:
        Player2Label1.setText(JDBConnection.JDBCGetPlayer(Player12.getText()));
    }//GEN-LAST:event_Player12KeyReleased

    private void Player13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player13KeyReleased
        // TODO add your handling code here:
        Player2Label2.setText(JDBConnection.JDBCGetPlayer(Player13.getText()));
    }//GEN-LAST:event_Player13KeyReleased

    private void Player14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player14KeyReleased
        // TODO add your handling code here:
        Player2Label3.setText(JDBConnection.JDBCGetPlayer(Player14.getText()));
    }//GEN-LAST:event_Player14KeyReleased

    private void Player15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player15KeyReleased
        // TODO add your handling code here:
        Player2Label4.setText(JDBConnection.JDBCGetPlayer(Player15.getText()));
    }//GEN-LAST:event_Player15KeyReleased

    private void Player16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player16KeyReleased
        // TODO add your handling code here:
        Player2Label5.setText(JDBConnection.JDBCGetPlayer(Player16.getText()));
    }//GEN-LAST:event_Player16KeyReleased

    private void Player17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player17KeyReleased
        // TODO add your handling code here:
        Player2Label6.setText(JDBConnection.JDBCGetPlayer(Player17.getText()));
    }//GEN-LAST:event_Player17KeyReleased

    private void Player18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player18KeyReleased
        // TODO add your handling code here:
        Player2Label7.setText(JDBConnection.JDBCGetPlayer(Player18.getText()));
    }//GEN-LAST:event_Player18KeyReleased

    private void Player19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player19KeyReleased
        // TODO add your handling code here:
        Player2Label8.setText(JDBConnection.JDBCGetPlayer(Player19.getText()));
    }//GEN-LAST:event_Player19KeyReleased

    private void Player20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player20KeyReleased
        // TODO add your handling code here:
        Player2Label9.setText(JDBConnection.JDBCGetPlayer(Player20.getText()));
    }//GEN-LAST:event_Player20KeyReleased

    private void Player21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player21KeyReleased
        // TODO add your handling code here:
        Player2Label10.setText(JDBConnection.JDBCGetPlayer(Player21.getText()));
    }//GEN-LAST:event_Player21KeyReleased

    private void Player22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Player22KeyReleased
        // TODO add your handling code here:
        Player2Label11.setText(JDBConnection.JDBCGetPlayer(Player22.getText()));
    }//GEN-LAST:event_Player22KeyReleased

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        int PID1=Integer.parseInt(Player1.getText());
        int PID2=Integer.parseInt(Player2.getText());
        int PID3=Integer.parseInt(Player3.getText());
        int PID4=Integer.parseInt(Player4.getText());
        int PID5=Integer.parseInt(Player5.getText());
        int PID6=Integer.parseInt(Player6.getText());
        int PID7=Integer.parseInt(Player7.getText());
        int PID8=Integer.parseInt(Player8.getText());
        int PID9=Integer.parseInt(Player9.getText());
        int PID10=Integer.parseInt(Player10.getText());
        int PID11=Integer.parseInt(Player11.getText());
        int PID12=Integer.parseInt(Player12.getText());
        int PID13=Integer.parseInt(Player13.getText());
        int PID14=Integer.parseInt(Player14.getText());
        int PID15=Integer.parseInt(Player15.getText());
        int PID16=Integer.parseInt(Player16.getText());
        int PID17=Integer.parseInt(Player17.getText());
        int PID18=Integer.parseInt(Player18.getText());
        int PID19=Integer.parseInt(Player19.getText());
        int PID20=Integer.parseInt(Player20.getText());
        int PID21=Integer.parseInt(Player21.getText());
        int PID22=Integer.parseInt(Player22.getText());        
        
        SADProjectCrickzie.CurrentMatchID = JDBConnection.JDBCCreateMatch( Team1ID ,Team2ID , Toss , PID1, PID2, PID3, PID4, PID5, PID6, PID7, PID8, PID9, PID10, PID11, PID12, PID13, PID14, PID15, PID16, PID17, PID18, PID19, PID20, PID21, PID22,Overs);
        this.setVisible(false);
        ScoreCard sc = new ScoreCard();
        sc.setVisible(true);
        ScoreUpdate su = new ScoreUpdate();
        su.setVisible(true);
    }//GEN-LAST:event_CreateActionPerformed

    private void AutoGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoGenActionPerformed
        // TODO add your handling code here:
        PlayerLabel1.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel2.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel3.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel4.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel5.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel6.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel7.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel8.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel9.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel10.setText(JDBConnection.JDBCGetPlayer(1));
        PlayerLabel11.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label1.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label2.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label3.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label4.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label5.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label6.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label7.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label8.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label9.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label10.setText(JDBConnection.JDBCGetPlayer(1));
        Player2Label11.setText(JDBConnection.JDBCGetPlayer(1));
        Player1.setText("1");
        Player2.setText("1");
        Player3.setText("1");
        Player4.setText("1");
        Player5.setText("1");
        Player6.setText("1");
        Player7.setText("1");
        Player8.setText("1");
        Player9.setText("1");
        Player10.setText("1");
        Player11.setText("1");
        Player12.setText("1");
        Player13.setText("1");
        Player14.setText("1");
        Player15.setText("1");
        Player16.setText("1");
        Player17.setText("1");
        Player18.setText("1");
        Player19.setText("1");
        Player20.setText("1");
        Player21.setText("1");
        Player22.setText("1");
    }//GEN-LAST:event_AutoGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PlayerSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoGen;
    private javax.swing.JButton Create;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Player1;
    private javax.swing.JTextField Player10;
    private javax.swing.JTextField Player11;
    private javax.swing.JTextField Player12;
    private javax.swing.JTextField Player13;
    private javax.swing.JTextField Player14;
    private javax.swing.JTextField Player15;
    private javax.swing.JTextField Player16;
    private javax.swing.JTextField Player17;
    private javax.swing.JTextField Player18;
    private javax.swing.JTextField Player19;
    private javax.swing.JTextField Player2;
    private javax.swing.JTextField Player20;
    private javax.swing.JTextField Player21;
    private javax.swing.JTextField Player22;
    private javax.swing.JLabel Player2Label1;
    private javax.swing.JLabel Player2Label10;
    private javax.swing.JLabel Player2Label11;
    private javax.swing.JLabel Player2Label2;
    private javax.swing.JLabel Player2Label3;
    private javax.swing.JLabel Player2Label4;
    private javax.swing.JLabel Player2Label5;
    private javax.swing.JLabel Player2Label6;
    private javax.swing.JLabel Player2Label7;
    private javax.swing.JLabel Player2Label8;
    private javax.swing.JLabel Player2Label9;
    private javax.swing.JTextField Player3;
    private javax.swing.JTextField Player4;
    private javax.swing.JTextField Player5;
    private javax.swing.JTextField Player6;
    private javax.swing.JTextField Player7;
    private javax.swing.JTextField Player8;
    private javax.swing.JTextField Player9;
    private javax.swing.JLabel PlayerLabel1;
    private javax.swing.JLabel PlayerLabel10;
    private javax.swing.JLabel PlayerLabel11;
    private javax.swing.JLabel PlayerLabel2;
    private javax.swing.JLabel PlayerLabel3;
    private javax.swing.JLabel PlayerLabel4;
    private javax.swing.JLabel PlayerLabel5;
    private javax.swing.JLabel PlayerLabel6;
    private javax.swing.JLabel PlayerLabel7;
    private javax.swing.JLabel PlayerLabel8;
    private javax.swing.JLabel PlayerLabel9;
    private javax.swing.JLabel Team1;
    private javax.swing.JLabel Team2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
