/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadprojectcrickzie;

/**
 *
 * @author User
 */
public final class ScoreUpdate extends javax.swing.JFrame {
    public int CurrentInnings=1;
    public int CurrentBatsmanSL1=1;
    public int CurrentBatsmanSL2=2;
    public int CurrentBowlerSL1=22;
    public int CurrentBowlerSL2=21;
    public int CurrentRun = 0;
    public String CurrentWicket = "NotOut";
    public int CurrentLegal = 0;
    public int CurrentBall = 0;
    public int CurrentOver = 0;
    int MID;
    /**
     * Creates new form ScoreUpdate
     */
    public ScoreUpdate() {
        initComponents();
        MID = SADProjectCrickzie.CurrentMatchID;
        ScorerUpdate();
    }
    
    /**
     *Scorer Window Gets Updated
     */
    public void ScorerUpdate(){
        Batsman1.setText(JDBConnection.JDBCGetPlayer(JDBConnection.JDBCGetPlayer(MID, CurrentBatsmanSL1)));
        Batsman2.setText(JDBConnection.JDBCGetPlayer(JDBConnection.JDBCGetPlayer(MID, CurrentBatsmanSL2)));
        Run1.setText(Integer.toString(JDBConnection.JDBCGetBatRun(MID, CurrentBatsmanSL1)));
        Run2.setText(Integer.toString(JDBConnection.JDBCGetBatRun(MID, CurrentBatsmanSL2)));
        Ball1.setText(Integer.toString(JDBConnection.JDBCGetBatBall(MID, CurrentBatsmanSL1)));
        Ball2.setText(Integer.toString(JDBConnection.JDBCGetBatBall(MID, CurrentBatsmanSL2)));
        Sixes1.setText(Integer.toString(JDBConnection.JDBCGetBatSixes(MID, CurrentBatsmanSL1)));
        Sixes2.setText(Integer.toString(JDBConnection.JDBCGetBatSixes(MID, CurrentBatsmanSL2)));
        Fours1.setText(Integer.toString(JDBConnection.JDBCGetBatFours(MID, CurrentBatsmanSL1)));
        Fours2.setText(Integer.toString(JDBConnection.JDBCGetBatFours(MID, CurrentBatsmanSL2)));
        TeamName.setText(JDBConnection.JDBCGetTeam(JDBConnection.JDBCGetTeamID(MID, 1)));
        TeamRun.setText(Integer.toString(JDBConnection.JDBCGetScore(MID, CurrentBatsmanSL1)));
        TeamWicket.setText(Integer.toString(JDBConnection.JDBCGetWicket(MID, CurrentBatsmanSL1)));
        TeamBall.setText(Integer.toString(CurrentBall));
        TeamOver.setText(Integer.toString(CurrentOver));
    }
    
    /**
     *
     * @param run
     * @param legal
     */
    public void disableWickets(int run,int legal){
        if(run != 0 || legal != 0){
            this.UpdateWicketNotOut.setEnabled(true);
            CurrentWicket = "NotOut";
            this.UpdateWicketNotOut.setSelected(true);
            this.UpdateWicketBowled.setSelected(false);
            this.UpdateWicketBowled.setEnabled(false);
            this.UpdateWicketCatch.setSelected(false);
            this.UpdateWicketCatch.setEnabled(false);
            this.UpdateWicketLBW.setSelected(false);
            this.UpdateWicketLBW.setEnabled(false);
            this.UpdateWicketStumped.setSelected(false);
            this.UpdateWicketStumped.setEnabled(false);
            this.UpdateWicketRunOut.setEnabled(true);
        }
        if(run >=4){
            this.UpdateWicketRunOut.setEnabled(false);
        }
        if(run == 0 && legal == 0){
            this.UpdateWicketBowled.setEnabled(true);
            //UpdateWicketNotOut.setSelected(true);
            //UpdateWicketBowled.setSelected(false);
            this.UpdateWicketBowled.setEnabled(true);
            //UpdateWicketCatch.setSelected(false);
            this.UpdateWicketCatch.setEnabled(true);
            //UpdateWicketLBW.setSelected(false);
            this.UpdateWicketLBW.setEnabled(true);
            //UpdateWicketStumped.setSelected(false);
            this.UpdateWicketStumped.setEnabled(true);
            //UpdateWicketRunOut.setSelected(true);
            this.UpdateWicketRunOut.setEnabled(true);
        }
        CurrentRun = run;
        CurrentLegal= legal;
    }
    public void NewBatsman(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Run = new javax.swing.ButtonGroup();
        Wicket = new javax.swing.ButtonGroup();
        Extra = new javax.swing.ButtonGroup();
        Batsman1 = new javax.swing.JLabel();
        Run1 = new javax.swing.JLabel();
        Ball1 = new javax.swing.JLabel();
        Sixes1 = new javax.swing.JLabel();
        Fours1 = new javax.swing.JLabel();
        Batsman2 = new javax.swing.JLabel();
        Run2 = new javax.swing.JLabel();
        Ball2 = new javax.swing.JLabel();
        Sixes2 = new javax.swing.JLabel();
        Fours2 = new javax.swing.JLabel();
        UpdateRun0 = new javax.swing.JToggleButton();
        UpdateRun1 = new javax.swing.JToggleButton();
        UpdateRun2 = new javax.swing.JToggleButton();
        UpdateRun3 = new javax.swing.JToggleButton();
        UpdateRun4 = new javax.swing.JToggleButton();
        UpdateRun6 = new javax.swing.JToggleButton();
        UpdateWicketNotOut = new javax.swing.JToggleButton();
        UpdateWicketCatch = new javax.swing.JToggleButton();
        UpdateWicketLBW = new javax.swing.JToggleButton();
        UpdateWicketStumped = new javax.swing.JToggleButton();
        UpdateWicketRunOut = new javax.swing.JToggleButton();
        UpdateExtraLegal = new javax.swing.JToggleButton();
        UpdateExtraWide = new javax.swing.JToggleButton();
        UpdateWicketBowled = new javax.swing.JToggleButton();
        UpdateExtraNo = new javax.swing.JToggleButton();
        SubmitBall = new javax.swing.JButton();
        TeamName = new javax.swing.JLabel();
        TeamRun = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TeamWicket = new javax.swing.JLabel();
        TeamOver = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TeamBall = new javax.swing.JLabel();

        setTitle("Scorer");

        Batsman1.setText("Batsman 1:");

        Run1.setText("0");

        Ball1.setText("0");

        Sixes1.setText("0");

        Fours1.setText("0");

        Batsman2.setText("Batsman 2:");

        Run2.setText("0");

        Ball2.setText("0");

        Sixes2.setText("0");

        Fours2.setText("0");

        Run.add(UpdateRun0);
        UpdateRun0.setMnemonic('0');
        UpdateRun0.setSelected(true);
        UpdateRun0.setText("0");
        UpdateRun0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun0ActionPerformed(evt);
            }
        });

        Run.add(UpdateRun1);
        UpdateRun1.setMnemonic('1');
        UpdateRun1.setText("1");
        UpdateRun1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun1ActionPerformed(evt);
            }
        });

        Run.add(UpdateRun2);
        UpdateRun2.setMnemonic('2');
        UpdateRun2.setText("2");
        UpdateRun2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun2ActionPerformed(evt);
            }
        });

        Run.add(UpdateRun3);
        UpdateRun3.setMnemonic('3');
        UpdateRun3.setText("3");
        UpdateRun3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun3ActionPerformed(evt);
            }
        });

        Run.add(UpdateRun4);
        UpdateRun4.setMnemonic('4');
        UpdateRun4.setText("4");
        UpdateRun4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun4ActionPerformed(evt);
            }
        });

        Run.add(UpdateRun6);
        UpdateRun6.setMnemonic('6');
        UpdateRun6.setText("6");
        UpdateRun6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateRun2MousePressed(evt);
            }
        });
        UpdateRun6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRun6ActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketNotOut);
        UpdateWicketNotOut.setSelected(true);
        UpdateWicketNotOut.setText("Not Out");
        UpdateWicketNotOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketNotOutActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketCatch);
        UpdateWicketCatch.setText("Catch");
        UpdateWicketCatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketCatchActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketLBW);
        UpdateWicketLBW.setText("LBW");
        UpdateWicketLBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketLBWActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketStumped);
        UpdateWicketStumped.setText("Stumped");
        UpdateWicketStumped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketStumpedActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketRunOut);
        UpdateWicketRunOut.setText("Run Out");
        UpdateWicketRunOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketRunOutActionPerformed(evt);
            }
        });

        Extra.add(UpdateExtraLegal);
        UpdateExtraLegal.setSelected(true);
        UpdateExtraLegal.setText("Legal");
        UpdateExtraLegal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateExtraWideMousePressed(evt);
            }
        });
        UpdateExtraLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExtraLegalActionPerformed(evt);
            }
        });

        Extra.add(UpdateExtraWide);
        UpdateExtraWide.setText("Wide");
        UpdateExtraWide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateExtraWideMousePressed(evt);
            }
        });
        UpdateExtraWide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExtraWideActionPerformed(evt);
            }
        });

        Wicket.add(UpdateWicketBowled);
        UpdateWicketBowled.setText("Bowled");
        UpdateWicketBowled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateWicketBowledActionPerformed(evt);
            }
        });

        Extra.add(UpdateExtraNo);
        UpdateExtraNo.setText("No");
        UpdateExtraNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UpdateExtraWideMousePressed(evt);
            }
        });
        UpdateExtraNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateExtraNoActionPerformed(evt);
            }
        });

        SubmitBall.setText("Submit");
        SubmitBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBallActionPerformed(evt);
            }
        });

        TeamName.setText("Team1:");

        TeamRun.setText("0");

        jLabel1.setText("/");

        TeamWicket.setText("0");

        TeamOver.setText("0");

        jLabel3.setText(".");

        TeamBall.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitBall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateRun6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UpdateRun1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(UpdateRun2))
                            .addComponent(UpdateRun3)
                            .addComponent(UpdateRun4)
                            .addComponent(UpdateRun0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UpdateWicketCatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateWicketLBW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateWicketRunOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateWicketStumped, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UpdateWicketNotOut, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UpdateWicketBowled, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Run1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Ball1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Run2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Ball2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateExtraLegal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Sixes2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Fours2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateExtraWide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateExtraNo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sixes1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Batsman1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(Batsman2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(TeamRun, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(Fours1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeamWicket, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(TeamOver, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeamBall, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamName)
                    .addComponent(TeamRun)
                    .addComponent(jLabel1)
                    .addComponent(TeamWicket)
                    .addComponent(TeamOver)
                    .addComponent(jLabel3)
                    .addComponent(TeamBall))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman1)
                    .addComponent(Run1)
                    .addComponent(Ball1)
                    .addComponent(Sixes1)
                    .addComponent(Fours1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batsman2)
                    .addComponent(Run2)
                    .addComponent(Ball2)
                    .addComponent(Sixes2)
                    .addComponent(Fours2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateRun0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateRun1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateRun2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateRun3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateRun4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UpdateExtraLegal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateExtraNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateExtraWide)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateRun6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateWicketNotOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateWicketBowled)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateWicketCatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateWicketLBW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateWicketStumped)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateWicketRunOut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(SubmitBall)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateRun0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun0ActionPerformed
        // TODO add your handling code here:
        disableWickets(0,CurrentLegal);
    }//GEN-LAST:event_UpdateRun0ActionPerformed

    private void UpdateRun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun1ActionPerformed
        // TODO add your handling code here:
        disableWickets(1,CurrentLegal);
    }//GEN-LAST:event_UpdateRun1ActionPerformed

    private void UpdateRun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun2ActionPerformed
        // TODO add your handling code here:
        disableWickets(2,CurrentLegal);
    }//GEN-LAST:event_UpdateRun2ActionPerformed

    private void UpdateRun3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun3ActionPerformed
        // TODO add your handling code here:
        disableWickets(3,CurrentLegal);
    }//GEN-LAST:event_UpdateRun3ActionPerformed

    private void UpdateRun4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun4ActionPerformed
        // TODO add your handling code here:
        disableWickets(4,CurrentLegal);
    }//GEN-LAST:event_UpdateRun4ActionPerformed

    private void UpdateRun6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRun6ActionPerformed
        // TODO add your handling code here:
        disableWickets(6,CurrentLegal);
    }//GEN-LAST:event_UpdateRun6ActionPerformed

    private void UpdateExtraLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExtraLegalActionPerformed
        // TODO add your handling code here:
        disableWickets(CurrentRun, 0);
        
    }//GEN-LAST:event_UpdateExtraLegalActionPerformed

    private void UpdateExtraWideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExtraWideActionPerformed
        // TODO add your handling code here:
        disableWickets(CurrentRun, 2);
        
    }//GEN-LAST:event_UpdateExtraWideActionPerformed

    private void UpdateExtraNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateExtraNoActionPerformed
        // TODO add your handling code here:
        disableWickets(CurrentRun, 1);
        
    }//GEN-LAST:event_UpdateExtraNoActionPerformed

    private void UpdateRun2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateRun2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateRun2MousePressed

    private void UpdateExtraWideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateExtraWideMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateExtraWideMousePressed

    private void UpdateWicketNotOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketNotOutActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "NotOut";
    }//GEN-LAST:event_UpdateWicketNotOutActionPerformed

    private void UpdateWicketBowledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketBowledActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "Bowled";
        
    }//GEN-LAST:event_UpdateWicketBowledActionPerformed

    private void UpdateWicketCatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketCatchActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "Catch";
    }//GEN-LAST:event_UpdateWicketCatchActionPerformed

    private void UpdateWicketLBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketLBWActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "LBW";
    }//GEN-LAST:event_UpdateWicketLBWActionPerformed

    private void UpdateWicketStumpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketStumpedActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "Stumped";
    }//GEN-LAST:event_UpdateWicketStumpedActionPerformed

    private void UpdateWicketRunOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateWicketRunOutActionPerformed
        // TODO add your handling code here:
        CurrentWicket = "RunOut";
    }//GEN-LAST:event_UpdateWicketRunOutActionPerformed
    private void PlayerSwap(){
        int temp=CurrentBatsmanSL1;
        CurrentBatsmanSL1=CurrentBatsmanSL2;
        CurrentBatsmanSL2=temp;
    }
    private void NextBatsman(){
        if(CurrentBatsmanSL1>CurrentBatsmanSL2){
            CurrentBatsmanSL1=CurrentBatsmanSL1+1;
        }
        else
            CurrentBatsmanSL1=CurrentBatsmanSL2+1;
    }
    private void BallChange(){
        CurrentBall+=1;
        if(CurrentBall>=6){
            NewOver();
        }
        
    }
    private void NewOver(){
        CurrentBall=0;
        CurrentOver+=1;
    }
    private void SubmitBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBallActionPerformed
        // TODO add your handling code here:
        JDBConnection.JDBCSetNewBall(MID, CurrentBatsmanSL1, CurrentBowlerSL1, CurrentRun, CurrentWicket, CurrentLegal);
        if(CurrentRun%2==1){
            PlayerSwap();
        }
        if(CurrentLegal>0){
            BallChange();
        }
        if(!"NotOut".equals(CurrentWicket)){
            NextBatsman();
        }
        System.out.println(CurrentBall+" "+CurrentLegal);
        ScorerUpdate();
    }//GEN-LAST:event_SubmitBallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ball1;
    private javax.swing.JLabel Ball2;
    private javax.swing.JLabel Batsman1;
    private javax.swing.JLabel Batsman2;
    private javax.swing.ButtonGroup Extra;
    private javax.swing.JLabel Fours1;
    private javax.swing.JLabel Fours2;
    private javax.swing.ButtonGroup Run;
    private javax.swing.JLabel Run1;
    private javax.swing.JLabel Run2;
    private javax.swing.JLabel Sixes1;
    private javax.swing.JLabel Sixes2;
    private javax.swing.JButton SubmitBall;
    private javax.swing.JLabel TeamBall;
    private javax.swing.JLabel TeamName;
    private javax.swing.JLabel TeamOver;
    private javax.swing.JLabel TeamRun;
    private javax.swing.JLabel TeamWicket;
    private javax.swing.JToggleButton UpdateExtraLegal;
    private javax.swing.JToggleButton UpdateExtraNo;
    private javax.swing.JToggleButton UpdateExtraWide;
    private javax.swing.JToggleButton UpdateRun0;
    private javax.swing.JToggleButton UpdateRun1;
    private javax.swing.JToggleButton UpdateRun2;
    private javax.swing.JToggleButton UpdateRun3;
    private javax.swing.JToggleButton UpdateRun4;
    private javax.swing.JToggleButton UpdateRun6;
    private javax.swing.JToggleButton UpdateWicketBowled;
    private javax.swing.JToggleButton UpdateWicketCatch;
    private javax.swing.JToggleButton UpdateWicketLBW;
    private javax.swing.JToggleButton UpdateWicketNotOut;
    private javax.swing.JToggleButton UpdateWicketRunOut;
    private javax.swing.JToggleButton UpdateWicketStumped;
    private javax.swing.ButtonGroup Wicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
